### PR TITLE
Support three  ^r152 color space

### PR DESCRIPTION
**Pull request by RodrigoHamuy**
Fixes https://github.com/tentone/geo-three/issues/67

Has backward compatibility with older threeJS versions too.

Followed the migration guides:

- https://github.com/mrdoob/three.js/wiki/Migration-Guide#151--152
- https://discourse.threejs.org/t/updates-to-color-management-in-three-js-r152/50791
- https://github.com/mrdoob/three.js/wiki/Migration-Guide#153--154

**How to test**: Install `three` r151 or r152. Look at any map.
**Before**: From r152, colours were washed out.
**Now**: Both should look identical.

### CODE REVIEW

**Comment by tentone** [comment]
Hello

Please remove any build related code from the PR.

The build will be later built and published

**Comment by RodrigoHamuy** [comment]
@tentone , done :)

**Comment by RodrigoHamuy** [comment]
@tentone build seems to fail under Node 12. I can reproduce this from `master` too so I don't think is related to this PR.
If you are happy I can bump the Github Action Node version to 16, which seems to work fine. Couldn't test with v14 for some unknown reason.

**Comment by tentone** [comment]
Thank you code looks good!

Merged!

**Pull request merged**
