### PR TITLE
Upgrade threejs version to 0.137.5

### PR DESCRIPTION
**Pull request by pramodcog**

### CODE REVIEW

**Comment by pramodcog** [comment]
@tentone Can we have this reviewed and merged on priority?

**Review by tentone — APPROVED** [review]
Changes look good! 

Thanks a lot!

**Comment by pramodcog** [comment]
@tentone Thank you, can you please release a new package for this

**Comment by tentone** [comment]
Yes I will release a new version to npm with this change in an hour. 

Thanks

**Pull request merged**
